<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Ingresar_spinner</name>
   <tag></tag>
   <elementGuidId>6d8e4251-0255-462d-9eb2-a9b48de4369a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;loadingOverlay&quot;]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.spinner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>48a2c4ff-27f2-4882-891b-3733c00b41dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>spinner</value>
      <webElementGuid>284cdf3e-f755-431d-9f43-2fefb5486fbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loadingOverlay&quot;)/div[@class=&quot;spinner&quot;]</value>
      <webElementGuid>b127e5c5-8234-469c-94c6-1cf683da8ce1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='loadingOverlay']/div</value>
      <webElementGuid>16b7a8c1-8650-4373-a45b-6133405e930f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/div</value>
      <webElementGuid>a2c55618-8b57-4888-955d-ec64425ed301</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
