<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cargar excel</name>
   <tag></tag>
   <elementGuidId>dc2ed695-df85-4571-9b7c-18193efd29e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='boton-dos']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#boton-dos</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>86a90eed-3534-42bb-8e7e-cdd4d0997e14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-falcon-default mt-2 me-2</value>
      <webElementGuid>6495b056-f527-46dd-b264-dec091c3b75b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f19562cf-eda2-4bbd-a3dc-9cf85142271a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>535daeea-e17c-4dc5-ba74-24fc17d12663</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#multiCollapse2</value>
      <webElementGuid>218e2d49-e8c5-4a38-991e-63ab0b961448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>544a01e7-2927-455f-8fe6-e27cc1cb2cfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>multiCollapse2</value>
      <webElementGuid>2edbab73-c3ba-4bfc-b15a-dbf2bb5e7a39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>boton-dos</value>
      <webElementGuid>68529b6a-05c3-49bf-b5ad-06a6c11b9f6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cargar excel </value>
      <webElementGuid>4b012676-ed36-4219-abf2-b54477f5f756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boton-dos&quot;)</value>
      <webElementGuid>6e90636d-cbaf-419a-bff4-6942675eac92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='boton-dos']</value>
      <webElementGuid>3b159785-0f6e-4377-825f-d919c29bd09f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-wizard-progress-tab1']/div/div/div[2]/button</value>
      <webElementGuid>6b12f867-3569-4bf9-9813-4b15230078d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Realizar pedido'])[1]/following::button[1]</value>
      <webElementGuid>c3765d6a-639b-4505-8b09-c17507ebc343</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Creación de Solicitudes'])[1]/following::button[1]</value>
      <webElementGuid>5ee23945-8e89-4af7-85f7-2be7131d2ec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Abrir Caso'])[1]/preceding::button[1]</value>
      <webElementGuid>5c6143b1-b6aa-44df-9648-e17eb5020fde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Indique dirección de destino. *'])[1]/preceding::button[1]</value>
      <webElementGuid>5ff78f60-720e-473f-9824-68c41b26e383</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cargar excel']/parent::*</value>
      <webElementGuid>41c4c897-51d7-41a4-ae4b-d4f7ad927683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>9c0e60ee-428e-4c0e-947c-a0ea9103a3dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'boton-dos' and (text() = 'Cargar excel ' or . = 'Cargar excel ')]</value>
      <webElementGuid>d9e17590-259e-426f-90a7-1bd45f61956e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
