<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_KIA</name>
   <tag></tag>
   <elementGuidId>853d96bc-d56b-4ac7-a6a9-b09abe04d966</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#marcaPedido-opt-41</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='marcaPedido-opt-41']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7bd0374f-aec0-4b34-93c4-51822b75b808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>41</value>
      <webElementGuid>1a99628f-25d2-403a-b2ed-1aa173c939b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option active</value>
      <webElementGuid>08c07bc6-3910-4bff-b03a-21cf58f2fa7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>abaa002d-8cd5-4ee9-8157-29f571fb01b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>marcaPedido-opt-41</value>
      <webElementGuid>b583f5bf-2ee9-4457-b3a5-ea3abb76c375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>93fc689d-4fd1-4cc7-bfed-f8b9822e8fec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KIA</value>
      <webElementGuid>ee57231c-d9df-4bfa-b94d-e3977814e7b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;marcaPedido-opt-41&quot;)</value>
      <webElementGuid>7867ef3b-577b-46f0-9336-173fa6651410</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='marcaPedido-opt-41']</value>
      <webElementGuid>93e801eb-e03a-4cc8-bf5b-4f6ad49e3b25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='marcaPedido-ts-dropdown']/div[41]</value>
      <webElementGuid>2627a239-228f-4111-9ad7-7196856ca929</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HYUNDAI'])[2]/following::div[1]</value>
      <webElementGuid>1e623aaf-d8f7-4036-9541-1f9950beb8a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DAEWOO'])[2]/following::div[2]</value>
      <webElementGuid>5f89b854-ed53-4520-89f5-9cb25a6c0956</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SAMSUNG'])[2]/preceding::div[1]</value>
      <webElementGuid>e33ed160-52be-413e-85f3-e3b521a7864e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SSANGYONG'])[2]/preceding::div[2]</value>
      <webElementGuid>ef713b67-b1a3-4080-9d6c-2448941fc459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[41]</value>
      <webElementGuid>fd5fcb7a-be17-4981-b4ed-9050960376d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'marcaPedido-opt-41' and (text() = 'KIA' or . = 'KIA')]</value>
      <webElementGuid>8afdbd32-f6bc-48f2-be76-fe64e69cc123</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
