<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Solicitudes Aprobadas</name>
   <tag></tag>
   <elementGuidId>6c2c06e8-78dd-4882-85a9-127bdfae83fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id='irMenu'])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>969de132-f11a-46d4-9e5f-5e46ee10af37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>irMenu</value>
      <webElementGuid>4b12a847-3a6f-4b19-87fd-ad7182729143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link </value>
      <webElementGuid>00348be3-1edc-465c-b333-11d10bd49f35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:actualizaVariableCodmodulo('../jsp/solucionador/solicitudesAprobadas.jsp')</value>
      <webElementGuid>928c670d-a48f-4fb3-b444-ca498b845149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:irmenu('102','/sales-orders/jsp/../jsp/solucionador/solicitudesAprobadas.jsp')</value>
      <webElementGuid>d28235d0-9342-483c-af67-65f11ec0c5a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Solicitudes Aprobadas</value>
      <webElementGuid>b6c51df3-8fcb-4249-b2a8-1b044ce4ca51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarVerticalNav&quot;)/li[@class=&quot;nav-item&quot;]/ul[@id=&quot;events3&quot;]/li[@class=&quot;nav-item&quot;]/a[@id=&quot;irMenu&quot;]</value>
      <webElementGuid>d4620aa8-78cd-469f-a441-535f20311797</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@id='irMenu'])[2]</value>
      <webElementGuid>b14c4e12-2ae6-4d92-b6e9-39f010300bee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//ul[@id='events3']/li/a[2])[2]</value>
      <webElementGuid>f5a89105-cc45-4e7b-88fe-7cd37f781fca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Solicitudes Aprobadas')]</value>
      <webElementGuid>cae11036-5536-4430-922d-fee936c7bc0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Solicitudes Recibidas'])[1]/following::a[2]</value>
      <webElementGuid>15ca0c97-8a2c-499a-8001-de2a42dd7ed6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Growix Finder'])[1]/following::a[4]</value>
      <webElementGuid>315fac49-f03d-4cc8-afab-e89ceb1c4ec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Solicitudes Enviadas'])[1]/preceding::a[2]</value>
      <webElementGuid>5f9de09e-4930-484b-98de-5c57afd26cc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buscar'])[1]/preceding::a[4]</value>
      <webElementGuid>3155c10b-6709-4a89-b198-d571ba930954</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Solicitudes Aprobadas']/parent::*</value>
      <webElementGuid>773c82de-ef02-49d3-8b84-96d0c4aade0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:irmenu('102','/sales-orders/jsp/../jsp/solucionador/solicitudesAprobadas.jsp')&quot;)]</value>
      <webElementGuid>61259022-d1ae-4b75-80aa-e41ba62d3597</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li/a[2]</value>
      <webElementGuid>1f9db9ba-33e8-4541-acd9-7c1a82847a2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'irMenu' and @href = concat(&quot;javascript:irmenu(&quot; , &quot;'&quot; , &quot;102&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;/sales-orders/jsp/../jsp/solucionador/solicitudesAprobadas.jsp&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Solicitudes Aprobadas' or . = 'Solicitudes Aprobadas')]</value>
      <webElementGuid>67e16ffd-e66a-4ab5-b263-974fd4422231</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
