<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Solicitudes Aprobadas</name>
   <tag></tag>
   <elementGuidId>6c2c06e8-78dd-4882-85a9-127bdfae83fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id='irMenu'])[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>07bdbd9a-627c-40ef-ba4b-701fb5bf83db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>irMenu</value>
      <webElementGuid>6063a25f-f80d-442e-aae6-880f954e542f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link </value>
      <webElementGuid>ebfc4c81-3154-4303-94d4-4887dfb64561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:actualizaVariableCodmodulo('../jsp/solucionador/solicitudesAprobadas.jsp')</value>
      <webElementGuid>d3413350-170f-40f2-bd62-1b687aa48769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:irmenu('102','/sales-orders/jsp/../jsp/solucionador/solicitudesAprobadas.jsp')</value>
      <webElementGuid>4ea0cd77-750d-40c7-8443-c68f726eefc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Solicitudes Aprobadas</value>
      <webElementGuid>5c2b1476-8af0-452f-9183-388399ff6034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarVerticalNav&quot;)/li[@class=&quot;nav-item&quot;]/ul[@id=&quot;events3&quot;]/li[@class=&quot;nav-item&quot;]/a[@id=&quot;irMenu&quot;]</value>
      <webElementGuid>87b263b3-8f9c-48b8-a083-f603e13434eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@id='irMenu'])[2]</value>
      <webElementGuid>6f601023-aaec-47c8-8446-d071b47a24a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//ul[@id='events3']/li/a[2])[2]</value>
      <webElementGuid>bf02a3b3-c697-48b4-a2f3-79847b581ef9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Solicitudes Aprobadas')]</value>
      <webElementGuid>5bef635f-f3b7-4ddd-aabf-add59bc56a24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Solicitudes Recibidas'])[1]/following::a[2]</value>
      <webElementGuid>3c619a81-693c-4e3e-9200-883fa4345aea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Growix Finder'])[1]/following::a[4]</value>
      <webElementGuid>034b3a27-41d4-4587-82cd-53ef89ce1281</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Solicitudes Enviadas'])[1]/preceding::a[2]</value>
      <webElementGuid>49f1f76a-0cb4-4799-a6f5-d1dd43001c52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buscar'])[1]/preceding::a[4]</value>
      <webElementGuid>c6ffae5e-c09e-4299-9ac3-f9b258bc54c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Solicitudes Aprobadas']/parent::*</value>
      <webElementGuid>46d95d98-36d0-4aed-b2df-e080c277edd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:irmenu('102','/sales-orders/jsp/../jsp/solucionador/solicitudesAprobadas.jsp')&quot;)]</value>
      <webElementGuid>9958211b-56a8-438e-b0fe-f6d8f2dd769b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li/a[2]</value>
      <webElementGuid>bf3b8ce6-f5ee-464f-8271-be180a3e55f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'irMenu' and @href = concat(&quot;javascript:irmenu(&quot; , &quot;'&quot; , &quot;102&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;/sales-orders/jsp/../jsp/solucionador/solicitudesAprobadas.jsp&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Solicitudes Aprobadas' or . = 'Solicitudes Aprobadas')]</value>
      <webElementGuid>11228667-a5c7-4607-85a6-b60fcba1b2e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
