<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nmero de pedido requerido_npedidoInput</name>
   <tag></tag>
   <elementGuidId>dc771349-f28d-4bf6-854b-ed2524fae234</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#npedidoInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='npedidoInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>57bbbcd0-87c3-4c86-9594-37e6c547ebad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>aed68511-3820-49f8-aca6-6ec0bf1379f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>npedidoInput</value>
      <webElementGuid>3e16e1c3-701a-43d1-bd36-e45fd9611ea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>swal2-input</value>
      <webElementGuid>9c76bb05-409e-43bf-8db7-42821c0d45aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ingrese el número de pedido</value>
      <webElementGuid>26f6a457-e8f8-424f-8c19-915972057cb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;npedidoInput&quot;)</value>
      <webElementGuid>7d4eaf21-6caf-4255-ad2e-7820b0505fce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='npedidoInput']</value>
      <webElementGuid>8fb77d9d-6e6b-441c-baec-b7e3789b4789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='swal2-html-container']/input</value>
      <webElementGuid>f061e236-3c1d-4276-8a71-f276aa1deb62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/div/div/div[2]/input</value>
      <webElementGuid>370b703c-4432-4101-9949-03b9bb1f56a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'npedidoInput' and @placeholder = 'Ingrese el número de pedido']</value>
      <webElementGuid>db27326b-0b77-4c67-8639-9418f2583105</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
