<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Entrega Estimada</name>
   <tag></tag>
   <elementGuidId>ecd7bac6-ab31-443b-9f72-8bb5171a8288</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.selectRow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tblSolicitudesPendientes']//tbody//tr[1]//input[@type='checkbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8419a460-2287-435b-af66-f2cd3d64ba53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>50d2fd8b-c38a-47cb-926d-130202bbe953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectRow</value>
      <webElementGuid>1f3fb2db-b091-4011-b898-46e353d369fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1070</value>
      <webElementGuid>a505739a-52cd-4d0a-a05b-30d70b65d2a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tblSolicitudesPendientes&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;sorting_1&quot;]/input[@class=&quot;selectRow&quot;]</value>
      <webElementGuid>a8ba170d-f3d3-4412-bc9f-b6344e94f32e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='1070']</value>
      <webElementGuid>be9b21fc-3cbe-4cb2-9815-c6df57e45f37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tblSolicitudesPendientes']/tbody/tr/td/input</value>
      <webElementGuid>af5b0cd5-d692-4510-adf1-988c03f84d89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>1cb0f316-69a6-4986-aee6-9602dcded538</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>def6c1fc-3a04-48b6-960b-baba0c50d958</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
