<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ciudad_ciudad</name>
   <tag></tag>
   <elementGuidId>7349ba1f-1c9a-428f-89ea-fe293d9b247f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ciudad']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ciudad</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f8d49e32-6556-49dd-b458-cf55074fb275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>list</name>
      <type>Main</type>
      <value>ciudadesList</value>
      <webElementGuid>93878e55-6f57-456d-9142-434dc2b38cc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ciudad</value>
      <webElementGuid>4cc95d78-bfb0-4e46-a9ff-97a1021f7fc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ciudad</value>
      <webElementGuid>a810ae34-def7-4ba6-9091-68b39ca27612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>5036ac21-5771-4780-bbe5-0b9c5c697a8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ciudad</value>
      <webElementGuid>9c55bfe2-2cbf-40ba-9746-941809e25317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personaNatural&quot;)/div[@class=&quot;row g-2&quot;]/div[@class=&quot;col-6&quot;]/div[@class=&quot;mb-3&quot;]/input[@id=&quot;ciudad&quot;]</value>
      <webElementGuid>2b5027e7-0518-435a-adb6-9fde3ef286b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ciudad']</value>
      <webElementGuid>cee4c9a7-240a-4462-9a75-9b0dacac672f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='personaNatural']/div[2]/div[2]/div/input</value>
      <webElementGuid>0bae2d08-be3b-4aab-ad6c-10002809c093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div[2]/div[2]/div/input</value>
      <webElementGuid>db778d86-a9ab-49c1-a13d-9c7cd898a3f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ciudad' and @name = 'ciudad' and @placeholder = 'Ciudad']</value>
      <webElementGuid>d9bd4f7c-59c0-46ad-b367-06c942ed634a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
