<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Telfono_telefono_sucursal</name>
   <tag></tag>
   <elementGuidId>c58f3515-4684-4287-87b2-704725f588b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='telefono_sucursal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#telefono_sucursal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>28fc992c-be0b-4221-aa40-dbbaea35be4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>502d0674-8ab5-4127-9bea-750946c0ca48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ec8400d7-3a9d-4bb2-bc0b-6bfe99a4e197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>telefono_sucursal</value>
      <webElementGuid>e4e1c26a-97ac-4675-a4d0-305b10915a01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>telefono_sucursal</value>
      <webElementGuid>0f4b0056-e649-43fa-9cdf-05694ed5468f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9\s]{3,15}</value>
      <webElementGuid>f414e736-1e57-41f6-ae00-8a3080f97afc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;telefono_sucursal&quot;)</value>
      <webElementGuid>33a01835-f439-4e46-9cf3-462b6a35b12c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='telefono_sucursal']</value>
      <webElementGuid>6e2e668d-f3bd-45fa-8bee-c6103baefe82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalSucursal']/div/div/div/div[2]/div[2]/div/div/input</value>
      <webElementGuid>6d8594f9-b6c3-444b-b7d4-e616a23c67ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/input</value>
      <webElementGuid>2805de80-deef-418f-94c8-4d41ab1dd488</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'telefono_sucursal' and @name = 'telefono_sucursal']</value>
      <webElementGuid>95a4d0d8-08a3-42c3-aca8-d91a507354a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
