<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Direccin_direccion_sucursal</name>
   <tag></tag>
   <elementGuidId>c8b00ccc-9ea0-4160-84d1-5c3e726c4bd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='direccion_sucursal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#direccion_sucursal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>532a08c8-3620-4196-985f-6749e20def76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>08ac834d-048b-4619-b02a-4bc2ff99b930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>26088c1b-34b7-420a-86c6-e320fd76a21b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>direccion_sucursal</value>
      <webElementGuid>0063d69a-b09b-4270-a416-f90a7c78a5e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>direccion_sucursal</value>
      <webElementGuid>de28d7e4-33ab-4651-af49-b28ac6d1bf4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;direccion_sucursal&quot;)</value>
      <webElementGuid>5fe01834-7f12-44c7-bee7-1a6cb8d2b991</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='direccion_sucursal']</value>
      <webElementGuid>51383e88-c3ed-46ce-8e13-667b302b1450</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalSucursal']/div/div/div/div[2]/div[3]/div/input</value>
      <webElementGuid>b38f320c-9dc0-4260-b958-7a65a37f6f65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/input</value>
      <webElementGuid>bf8f0c19-1548-49a1-a3b5-9f11eae0458a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'direccion_sucursal' and @name = 'direccion_sucursal']</value>
      <webElementGuid>245699de-d2a1-49db-8472-8733b902837c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
