<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Documento de identificacin_documento__67a552</name>
   <tag></tag>
   <elementGuidId>4c262879-d709-4bcd-839e-ac2c23fb9385</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='documento_identificacion']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#documento_identificacion</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7a82c5a1-1980-487f-b839-95e0bd22bb7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>44e002e9-ff4a-4513-8205-51dbdd032ba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>documento_identificacion</value>
      <webElementGuid>bfd8dde4-9728-4d83-b82f-8373c977cfc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>80c3bbb8-bcf4-4787-a612-80b595442ca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>documento_identificacion</value>
      <webElementGuid>9f8ac40a-4b6a-4614-b098-d38c39889550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:valida_crear_Cliente()</value>
      <webElementGuid>a4aa586e-2fbe-4b05-91ed-26ab91988210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>921b7b0e-8b89-43fe-87c7-8f37356d81f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>3cfdcad2-4e55-4889-bf01-182ce81aeec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Documento</value>
      <webElementGuid>877ddff1-d96e-46dc-b276-ded09e75357b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personaNatural&quot;)/div[@class=&quot;row g-2&quot;]/div[@class=&quot;col-6&quot;]/div[@class=&quot;mb-3&quot;]/input[@id=&quot;documento_identificacion&quot;]</value>
      <webElementGuid>7207120b-6d47-42e4-be6f-eeaa2168a950</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='documento_identificacion']</value>
      <webElementGuid>e6dec7c9-fae7-4e43-8ef0-3a21e02baacc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='personaNatural']/div/div/div/input</value>
      <webElementGuid>a5bd59be-95d3-4415-be58-7ed693572328</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div/div/input</value>
      <webElementGuid>308d33bb-0694-4c39-aa9e-5e37748f8a74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'documento_identificacion' and @type = 'text' and @name = 'documento_identificacion' and @placeholder = 'Documento']</value>
      <webElementGuid>ab0e9865-b155-48d8-b61e-814fcc33216d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
