<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ciudad_ciudad_sucursal</name>
   <tag></tag>
   <elementGuidId>98d5c8ea-21d6-4c40-adcc-01a6b3e5b672</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ciudad_sucursal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ciudad_sucursal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>38e7f002-b714-4cc2-bed2-7751ddf6f525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>list</name>
      <type>Main</type>
      <value>ciudadesList</value>
      <webElementGuid>4a82ea50-cf2b-44b1-9439-ddbf10ccc0a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ciudad_sucursal</value>
      <webElementGuid>4d41bed0-9162-49fe-9ad9-2a0afcc72169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ciudad_sucursal</value>
      <webElementGuid>9bdb5513-3471-46c5-bced-beb2d6a2d4ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ec06799f-0870-4e22-8eb4-7365cac26e95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ciudad</value>
      <webElementGuid>503c3dc6-1af0-42ac-a4a6-0cc7ab4caed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ciudad_sucursal&quot;)</value>
      <webElementGuid>aa59bdaa-5c58-4361-b032-034646553641</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ciudad_sucursal']</value>
      <webElementGuid>71aee2c4-790e-4c87-b02c-c3a7546271d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalSucursal']/div/div/div/div[2]/div[2]/div[2]/div/input</value>
      <webElementGuid>7964ef42-4699-4be2-9287-a2d799357ef6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>75391cfe-9dce-4812-bdb1-1923d53cf20c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ciudad_sucursal' and @name = 'ciudad_sucursal' and @placeholder = 'Ciudad']</value>
      <webElementGuid>f87b55b9-1ab5-42f7-9503-c4c97ab2019b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
