<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tipo de Sucursal_tipo_sucursal</name>
   <tag></tag>
   <elementGuidId>272f4e95-1bbd-455e-8a02-c95f145e26f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tipo_sucursal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tipo_sucursal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bd3a3c8c-af7e-4aa5-a2f2-575dff70b008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ccfedbc0-32f6-452f-b359-5be8f75e2dd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>03b6b210-fd58-457e-8c68-110b6bcc7dcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tipo_sucursal</value>
      <webElementGuid>e9616f38-f9f7-4bf7-94bb-e4496bf66d16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tipo_sucursal</value>
      <webElementGuid>c3871c6b-3180-4b82-a6f6-57bed84ea74c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tipo_sucursal&quot;)</value>
      <webElementGuid>c33928ca-07a0-4d6b-9ea9-1a07590c6415</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tipo_sucursal']</value>
      <webElementGuid>5cdc7f17-b084-40c0-83db-2f200800457a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalSucursal']/div/div/div/div[2]/div[4]/div/div/input</value>
      <webElementGuid>9d9272b4-9848-4338-821a-0b453f42e4eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>e7215188-fed3-42db-8aa4-f35f1f844a5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'tipo_sucursal' and @name = 'tipo_sucursal']</value>
      <webElementGuid>2c07edf8-af9c-440b-8060-a309dbcccd69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
