<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Direccin del Cliente_direccion</name>
   <tag></tag>
   <elementGuidId>802ffb47-883c-4d1f-810c-2cb5dda42512</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='direccion']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#direccion</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9de133b2-e2bd-49c0-b0bc-be7220aeae24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3abdf732-8155-4e76-8cba-0d346d8e15be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>90d10b36-d98a-4293-9c3e-9ca79a8e13a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>direccion</value>
      <webElementGuid>d2b3e3ba-fefb-4002-9f7d-00e05b215cbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>direccion</value>
      <webElementGuid>db0ca3b0-dd00-47d4-9e9b-7013d79d0089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>150b86e0-a76f-4906-8259-9bdb07352bec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Direccion</value>
      <webElementGuid>4e2b710c-f8f7-4ad0-83d4-198cd0359cf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personaNatural&quot;)/div[@class=&quot;row g-2&quot;]/div[@class=&quot;row g-2&quot;]/div[@class=&quot;mb-3&quot;]/input[@id=&quot;direccion&quot;]</value>
      <webElementGuid>eb81e82a-63ff-4485-8da1-a3a224e2ff51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='direccion']</value>
      <webElementGuid>e05b41c4-aba7-4955-9216-b7d5a255233f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='personaNatural']/div[2]/div[3]/div/input</value>
      <webElementGuid>20426f84-8402-4299-afc2-a1951574d77d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[3]/div/input</value>
      <webElementGuid>7b054256-a044-42f0-8f0f-b013e0af3eb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'direccion' and @id = 'direccion' and @placeholder = 'Direccion']</value>
      <webElementGuid>e9275966-dd4b-4dce-af90-c61f2411d2e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
