<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Selecciona su estado                _5dd4ee</name>
   <tag></tag>
   <elementGuidId>ac7c453e-8b3a-4699-9dde-fd532506feb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='activo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#activo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>22f0f3d5-2070-4a45-87c0-3b15ac7b0427</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>95216cd5-ceb5-40a9-8fd5-26ab2061d588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-options</name>
      <type>Main</type>
      <value>{&quot;removeItemButton&quot;:true,&quot;placeholder&quot;false}</value>
      <webElementGuid>da19ab09-f0d4-4c95-b25c-4ee67c777ae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>activo</value>
      <webElementGuid>68aab0ca-6736-4b4d-96ce-f1526254eb3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>activo</value>
      <webElementGuid>80bab0e5-a7fa-4a87-b2cd-fec26917c784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>dbf8ed31-fcf5-48f1-9f32-b67a88603ba2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                    Selecciona su estado
                                                                    Activo
                                                                    Inactivo
                                                                </value>
      <webElementGuid>b0626120-31d9-4273-a55c-30cfb98f8db4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personaNatural&quot;)/div[@class=&quot;row g-2&quot;]/div[@class=&quot;col-6&quot;]/div[@class=&quot;mb-3&quot;]/select[@id=&quot;activo&quot;]</value>
      <webElementGuid>35be9916-b09d-4a3f-9ac8-0033bda49687</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='activo']</value>
      <webElementGuid>57afdbb6-315d-4ce1-84b1-1591ed964f9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='personaNatural']/div/div[2]/div/select</value>
      <webElementGuid>a03f0679-f798-48eb-9d76-99acff699620</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estado'])[1]/following::select[1]</value>
      <webElementGuid>265af247-9a7c-4aba-a19f-fcfdfd437b86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Especifique el documento de identificacion'])[1]/following::select[1]</value>
      <webElementGuid>00007563-30fb-4992-b993-f93b2cb8bfcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccione el estado del Cliente (Activo / Inactivo)'])[1]/preceding::select[1]</value>
      <webElementGuid>cfc3c43e-6e5e-4467-8300-10b3cda146c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nombre Completo'])[1]/preceding::select[1]</value>
      <webElementGuid>b8ed1a3f-d7f2-409a-9d9b-07ebb935c11b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div[2]/div/select</value>
      <webElementGuid>e5eda2ab-11a9-4ed7-82d2-3ccbc442854c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'activo' and @id = 'activo' and (text() = '
                                                                    Selecciona su estado
                                                                    Activo
                                                                    Inactivo
                                                                ' or . = '
                                                                    Selecciona su estado
                                                                    Activo
                                                                    Inactivo
                                                                ')]</value>
      <webElementGuid>db87e14a-3fd9-477b-8d7c-f7a5e8b1cbf5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
