<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>2c14af17-f617-407f-9067-afbe0f12c390</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='top']/div/nav/div/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;logo&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0517cb81-1804-4f83-b310-0bbbfad2e1da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/sales-orders/images/logo-tracking-1.png</value>
      <webElementGuid>ce582c0e-014e-4423-a220-ca2bc78f3877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>a3d8cb53-e108-421e-943e-1ec8bf535b66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>f1cb0106-c912-43da-bcb8-87c5ef12a77b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top&quot;)/div[@class=&quot;container&quot;]/nav[@class=&quot;navbar navbar-light navbar-vertical navbar-expand-xl navbar-card&quot;]/div[@class=&quot;d-flex align-items-center&quot;]/a[@class=&quot;navbar-brand&quot;]/div[@class=&quot;d-flex align-items-center rectangle&quot;]/img[1]</value>
      <webElementGuid>e1d5fed5-7a58-494a-b972-e93e8d01215b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='top']/div/nav/div/a/div/img</value>
      <webElementGuid>636b956a-9532-47c6-838a-31c857ba1bac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='logo']</value>
      <webElementGuid>ccdd37bf-d9e6-4ed8-9894-5a107893b815</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>afec2678-9d83-44d1-bc27-2d0e1de89bf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/sales-orders/images/logo-tracking-1.png' and @alt = 'logo']</value>
      <webElementGuid>cc91b530-7945-426a-949b-d922302d6493</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
