<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Mis Solicitudes Cotizadas</name>
   <tag></tag>
   <elementGuidId>5becc0cc-954e-45cb-9191-a67626f9f10c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id='irMenu'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>734e530e-8607-4132-b472-9ca979b82902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>irMenu</value>
      <webElementGuid>747c944e-2522-4456-a393-65c2b4ff7df9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link </value>
      <webElementGuid>4fd9864f-b01d-44b0-b529-3e8f3d98be37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:actualizaVariableCodmodulo('../jsp/cliente/misSolicitudesCotizadas.jsp')</value>
      <webElementGuid>cde70099-d044-4534-9345-0a0627ee7879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:irmenu('101','/sales-orders/jsp/../jsp/cliente/misSolicitudesCotizadas.jsp')</value>
      <webElementGuid>40c1fa3a-ea29-44e4-acc3-49fd9030c196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mis Solicitudes Cotizadas</value>
      <webElementGuid>cbb512bf-e2ab-4234-8c86-5f2b2161bf41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarVerticalNav&quot;)/li[@class=&quot;nav-item&quot;]/ul[@id=&quot;events15&quot;]/li[@class=&quot;nav-item&quot;]/a[@id=&quot;irMenu&quot;]</value>
      <webElementGuid>16418271-aedb-422f-ab1c-69e902bfae42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@id='irMenu'])[3]</value>
      <webElementGuid>a0b02d69-7300-4298-a7f2-ec0134fc5a25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//ul[@id='events15']/li/a[2])[3]</value>
      <webElementGuid>62539961-81f3-4b06-858e-446b44956270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Mis Solicitudes Cotizadas')]</value>
      <webElementGuid>8756f239-bb5e-47fa-b7b1-f7f756229299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mis Solicitudes Pendientes'])[1]/following::a[2]</value>
      <webElementGuid>b88cbd58-dbea-4231-8b65-a4381d45b249</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Crear Solicitud'])[1]/following::a[4]</value>
      <webElementGuid>c8f91df0-e908-4f00-aa36-7bc5612ad62f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Solicitudes Tracking'])[1]/preceding::a[2]</value>
      <webElementGuid>e9e6706b-1108-45a8-b2fc-a7de3151c387</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buscar'])[1]/preceding::a[4]</value>
      <webElementGuid>db60cdb8-4963-4ef7-a421-2fad2858d074</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mis Solicitudes Cotizadas']/parent::*</value>
      <webElementGuid>ee1316ea-1073-4164-9363-62d1d7fea931</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:irmenu('101','/sales-orders/jsp/../jsp/cliente/misSolicitudesCotizadas.jsp')&quot;)]</value>
      <webElementGuid>98fd27ce-aa5f-438e-8437-121b47bbd2f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[3]/li/a[2]</value>
      <webElementGuid>2357ca77-f274-44a1-b04a-c0595a5840ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'irMenu' and @href = concat(&quot;javascript:irmenu(&quot; , &quot;'&quot; , &quot;101&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;/sales-orders/jsp/../jsp/cliente/misSolicitudesCotizadas.jsp&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Mis Solicitudes Cotizadas' or . = 'Mis Solicitudes Cotizadas')]</value>
      <webElementGuid>b4d07157-3dd8-44ea-be7b-f10ebeccd077</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
