<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Mis Solicitudes Cotizadas</name>
   <tag></tag>
   <elementGuidId>5becc0cc-954e-45cb-9191-a67626f9f10c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id='irMenu'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dbebfd37-7f39-4b2e-aed5-af8fde9f2600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>irMenu</value>
      <webElementGuid>da638f9f-7ae1-4b2f-be31-df9d9aac2d61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link </value>
      <webElementGuid>2e97e654-545b-48bc-bd85-9a5e48fc857d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:actualizaVariableCodmodulo('../jsp/cliente/misSolicitudesCotizadas.jsp')</value>
      <webElementGuid>76175808-0028-4150-bab2-e6b37a3ca3ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:irmenu('101','/sales-orders/jsp/../jsp/cliente/misSolicitudesCotizadas.jsp')</value>
      <webElementGuid>2d7df7f6-5d00-47aa-b12b-1c1164142089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mis Solicitudes Cotizadas</value>
      <webElementGuid>a46ebc8e-9847-4894-8428-0451fb2c6131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarVerticalNav&quot;)/li[@class=&quot;nav-item&quot;]/ul[@id=&quot;events15&quot;]/li[@class=&quot;nav-item&quot;]/a[@id=&quot;irMenu&quot;]</value>
      <webElementGuid>8f037070-c254-4ce1-90e1-01a914756b4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@id='irMenu'])[3]</value>
      <webElementGuid>9c922bac-ae82-4eb2-b37e-01e1de3456ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//ul[@id='events15']/li/a[2])[3]</value>
      <webElementGuid>95d1707e-853c-4a36-a3a8-60cef14c2890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Mis Solicitudes Cotizadas')]</value>
      <webElementGuid>11324342-4e24-4708-b22a-98069a6017a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mis Solicitudes Pendientes'])[1]/following::a[2]</value>
      <webElementGuid>5259d7c2-ae48-4fd2-8356-2004f221d35b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Crear Solicitud'])[1]/following::a[4]</value>
      <webElementGuid>b2cebd6f-1807-43db-bc4a-4adca919ad5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Solicitudes Tracking'])[1]/preceding::a[2]</value>
      <webElementGuid>5fe40eb3-dca0-4a4c-bde7-8e6055e1c9be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buscar'])[1]/preceding::a[4]</value>
      <webElementGuid>c8ee9c8a-170a-4599-9fda-19f4d37dc4e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mis Solicitudes Cotizadas']/parent::*</value>
      <webElementGuid>7d6940f6-7a16-4e0e-a51d-0757cdfd98dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:irmenu('101','/sales-orders/jsp/../jsp/cliente/misSolicitudesCotizadas.jsp')&quot;)]</value>
      <webElementGuid>f14055bd-eb0d-4447-b3b2-4870f6352ef6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[3]/li/a[2]</value>
      <webElementGuid>0fdd6cc8-cd2e-483a-a260-7fe023f13f20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'irMenu' and @href = concat(&quot;javascript:irmenu(&quot; , &quot;'&quot; , &quot;101&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;/sales-orders/jsp/../jsp/cliente/misSolicitudesCotizadas.jsp&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Mis Solicitudes Cotizadas' or . = 'Mis Solicitudes Cotizadas')]</value>
      <webElementGuid>ee8c16e9-bd84-49f1-b858-8dcf96e7cffb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
