<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Aceptar</name>
   <tag></tag>
   <elementGuidId>bd90ad92-fab3-44e1-9409-dddcd0e73652</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tblDetalleSolicitud']/tbody/tr/td[12]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-success.btn-aceptar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a404a8dc-9ada-4ac6-8d8a-96fb2093788b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success btn-aceptar</value>
      <webElementGuid>5695e030-ce78-4483-907b-d9a7c66e34f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id-detalle</name>
      <type>Main</type>
      <value>1046</value>
      <webElementGuid>96ebba83-fcfa-4259-a606-c1fa12a1f3a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-accion</name>
      <type>Main</type>
      <value>aceptar</value>
      <webElementGuid>a9b3f45d-9633-4d51-a7da-71a0fca85767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Aceptar</value>
      <webElementGuid>63086417-eddd-4cbe-96a2-147bb7afe96f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tblDetalleSolicitud&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[12]/button[@class=&quot;btn btn-success btn-aceptar&quot;]</value>
      <webElementGuid>b06cf3e2-b1c9-4bcd-982f-1070864be23a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tblDetalleSolicitud']/tbody/tr/td[12]/button</value>
      <webElementGuid>abcee34f-1132-4ebc-b1a7-3e5a0b555489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$51,600.00'])[1]/following::button[1]</value>
      <webElementGuid>0bdc87ff-8657-4589-9141-716ef712b699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$44,000.00'])[1]/following::button[1]</value>
      <webElementGuid>fc8caa18-f967-4642-aea0-717d113eae32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rechazar'])[1]/preceding::button[1]</value>
      <webElementGuid>d1f04ffe-fad0-4421-be7a-9e5c3945c366</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1 to 1 of 1 entries'])[1]/preceding::button[2]</value>
      <webElementGuid>ad33d81a-fa91-46c4-8a5a-0f2da5d3eba4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Aceptar']/parent::*</value>
      <webElementGuid>347daa07-9364-4d77-9a2c-3158be5cf3f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[12]/button</value>
      <webElementGuid>4fedf5b5-cf5a-4d48-ae9a-e53c8ecffa0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' Aceptar' or . = ' Aceptar')]</value>
      <webElementGuid>02daebeb-9a94-4607-975c-6a2fbab943e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
