<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Guardar Cambios</name>
   <tag></tag>
   <elementGuidId>1629fdfa-db19-485c-9bc1-b7c6f1c39ac3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='nuevo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nuevo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>04e1fd4b-c668-43cb-be4a-cdfc30f7a832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nuevo</value>
      <webElementGuid>28ab8839-fb83-49ad-aa79-3cb0dc30e976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nuevo</value>
      <webElementGuid>bf18b8a3-bffc-4f57-8afa-287932d0bdb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8995b926-d527-4b50-85ba-2c8be9725e89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnAnimado mt-4 mb-4 bt-4</value>
      <webElementGuid>964dcd8d-f62e-44b0-bc4e-8488f33a3238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:actualiza()</value>
      <webElementGuid>2e579f4d-c52c-47a0-8501-8666b46659ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Guardar Cambios</value>
      <webElementGuid>2cc4fb2e-e96f-4407-9ec4-b0b5ca4729bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nuevo&quot;)</value>
      <webElementGuid>670d51cd-03c4-4bb6-a9f6-b6557922b5bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='nuevo']</value>
      <webElementGuid>4591d678-ae30-4396-88bb-0e3a10d751c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frm']/button</value>
      <webElementGuid>e5ce9530-0af2-4e2f-9870-e1b4053d7566</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mis Solicitudes Growix'])[2]/following::button[1]</value>
      <webElementGuid>e4583cf6-6400-4e5b-953d-779a7fe21553</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Growix Finder'])[2]/following::button[1]</value>
      <webElementGuid>27e93737-1c9a-456d-bac2-34c2e79e79f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Guardar Cambios']/parent::*</value>
      <webElementGuid>f428ebaf-d101-400f-9776-c3629a5785ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
      <webElementGuid>9e0ab222-e7fe-41fe-9498-23415faedc8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'nuevo' and @id = 'nuevo' and @type = 'button' and (text() = 'Guardar Cambios' or . = 'Guardar Cambios')]</value>
      <webElementGuid>3987b39c-2264-4515-9e00-4feb2eeb2345</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
