<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Crear Usuario</name>
   <tag></tag>
   <elementGuidId>5a83e0e2-cdc9-4cba-b8a5-496594d0c9d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-falcon-primary.me-1.mb-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;top&quot;]/div/div/div[4]/form/div[1]/div[3]/div[3]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0c400a77-5ca1-4fb7-9309-4b08c0eac17c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>25530513-cc8f-4600-abe9-52451fb88d5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>3f43253b-a736-4966-a589-91cbbd7b49c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:nuevoUser()</value>
      <webElementGuid>54d0c636-0ed1-4660-ac36-acb5c837d9bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-falcon-primary me-1 mb-1</value>
      <webElementGuid>75e36a98-b084-4b10-90c1-6c20967da13b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip928926</value>
      <webElementGuid>9e965dd4-f876-4b09-8e7d-0b803e29c4eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Crear Usuario </value>
      <webElementGuid>eeff20c5-6498-409e-a720-de4fedc608a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;card mb-3 mt-3&quot;]/form[1]/div[@class=&quot;container mt-5&quot;]/div[@class=&quot;row align-items-center&quot;]/div[@class=&quot;col-md-2 mt-4&quot;]/div[@class=&quot;form-group&quot;]/button[@class=&quot;btn btn-falcon-primary me-1 mb-1&quot;]</value>
      <webElementGuid>dd3c1d2e-eb7c-401f-8355-49d53b77fff4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[5]</value>
      <webElementGuid>cae0e3a5-78a5-4da5-8ba0-f71cbdebe230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='top']/div/div/div[4]/form/div/div[3]/div[3]/div/button</value>
      <webElementGuid>4de3ea59-46be-4766-a0ac-2984c84d5109</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NIKOLAS ESTEBAN KREJCI BAUTISTA'])[1]/following::button[1]</value>
      <webElementGuid>e275b4ff-ee6e-47de-9f7b-105d038c2c14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IDL-SAS'])[1]/following::button[1]</value>
      <webElementGuid>2485d88b-8856-4eb8-8d0d-51078e54e328</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Editar'])[1]/preceding::button[1]</value>
      <webElementGuid>eeef16fb-4472-478d-94e4-214e40122b04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Codigo de Usuario'])[1]/preceding::button[1]</value>
      <webElementGuid>135c8a4e-8fe4-40de-8189-588fd6d1bb73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Crear Usuario']/parent::*</value>
      <webElementGuid>fd6e8825-1a6c-471d-af5b-1cfa90848d54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button</value>
      <webElementGuid>2c51aeae-e526-450c-aed4-aa1fa793105a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Crear Usuario ' or . = 'Crear Usuario ')]</value>
      <webElementGuid>365859e5-8efe-4686-b8b5-4ae7ea542f52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
