<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_BOGOT - BOGOT - CALLE SIEMPRE VIVA 145</name>
   <tag></tag>
   <elementGuidId>0990f408-5ed9-4cb6-96d6-c1b185e9b74a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sucursal-opt-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sucursal-opt-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a24bf9d8-d575-4349-8ffc-96f8c67548f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>19</value>
      <webElementGuid>48f1f234-ef7f-4683-959d-26489ebd93ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option active</value>
      <webElementGuid>68e71d13-f17b-4491-991f-33fd83667546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>6f55cec8-690a-4a35-9dbc-ebb5cc8da1c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sucursal-opt-1</value>
      <webElementGuid>f88b1df7-e588-4674-ace6-6a8d0109feb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9e6c963a-cece-4dad-a638-ecf938726dab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BOGOTÁ - BOGOTÁ - CALLE SIEMPRE VIVA 145</value>
      <webElementGuid>758425bd-1d1a-4c1b-8757-a1557f599c7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sucursal-opt-1&quot;)</value>
      <webElementGuid>17912f42-2fb2-4588-b94d-f4ea79447c09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='sucursal-opt-1']</value>
      <webElementGuid>008b02eb-3a3e-4e56-ac30-cc30b7fa8f1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sucursal-ts-dropdown']/div</value>
      <webElementGuid>d43ef08d-f4e6-493b-a476-6ac9ec04f190</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sucursal del Cliente:'])[1]/following::div[5]</value>
      <webElementGuid>c9000829-cf93-4000-8bc9-b12d0c579efd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cliente al que va a hacer Parte'])[1]/following::div[8]</value>
      <webElementGuid>f1681dff-5a84-4115-8906-f558a5630ffa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccione la(s) sucursal(es) a la que va a hacer parte este Usuario'])[1]/preceding::div[1]</value>
      <webElementGuid>4e4ba5cc-9158-40ac-b2ff-0ce9a1dbfa4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='País:'])[1]/preceding::div[2]</value>
      <webElementGuid>b5981b43-4b6d-4814-a27f-837a9b4e02d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div/div/div[2]/div/div</value>
      <webElementGuid>3e549956-98df-4a4f-99ed-d5a841b2ff33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'sucursal-opt-1' and (text() = 'BOGOTÁ - BOGOTÁ - CALLE SIEMPRE VIVA 145' or . = 'BOGOTÁ - BOGOTÁ - CALLE SIEMPRE VIVA 145')]</value>
      <webElementGuid>9e437135-8397-4d8a-9097-49c469d82b45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
