<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nombre de Usuario_nombreUsuario</name>
   <tag></tag>
   <elementGuidId>00bee87e-b9af-4f96-8abf-deb9594cc0ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nombreUsuario']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nombreUsuario</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fccaa981-3985-4cac-bca4-c108a25b154a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>5a9e1d7f-cecc-4d2b-a004-7b055f4036ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nombreUsuario</value>
      <webElementGuid>78c4d45e-7e97-4d38-9862-55cbed62a9c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nombreUsuario</value>
      <webElementGuid>df075247-45e9-471e-a025-283e2d9d5eca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>27c84405-e7e7-4bf5-adf2-6c3302a870ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nombre</value>
      <webElementGuid>b6207b6b-5769-43e7-b1c3-3812747da9bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b456ee7d-1579-4f03-a6c8-4ca1d7ac5c91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>747d3d4e-95c6-483b-b4e8-f7c56896685e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^\S{1,50}$</value>
      <webElementGuid>3e0e1c56-7cc2-4656-859d-a39c522b010a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>this.value = this.value.replace(/\s/g, '')</value>
      <webElementGuid>180a09fb-fd50-4b8b-bbfa-7776d1fcab0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nombreUsuario&quot;)</value>
      <webElementGuid>57e2aa9e-920c-4a50-a981-0ebaa0358069</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nombreUsuario']</value>
      <webElementGuid>4aea9426-9eb0-49fc-b04b-3eaddace4cea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frm']/div[3]/div/div/input</value>
      <webElementGuid>f8dce79e-5762-4d3a-9778-8aec52094c6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>4294dec9-4a2d-463b-8360-1706bf69b21e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'nombreUsuario' and @id = 'nombreUsuario' and @placeholder = 'Nombre' and @type = 'text']</value>
      <webElementGuid>738b2ec2-7a37-48f7-9c5b-1621dc48cffd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
