<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_DONPEDRO</name>
   <tag></tag>
   <elementGuidId>e1e50b6e-8e38-4f1c-a2d1-4f716b1ee6d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='codigosap']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#codigosap</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0f1030c9-b2fd-4a60-9a4c-57fae0c0c08b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select js-choice choices__input</value>
      <webElementGuid>7a2819ee-91ee-406f-bdfa-7a1b7460c02f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>codigosap</value>
      <webElementGuid>7bb24bc0-6fa5-4331-a825-1a23be4477e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>codigosap</value>
      <webElementGuid>635a3699-d2da-4055-8f35-ec8f5504efa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-options</name>
      <type>Main</type>
      <value>{&quot;removeItemButton&quot;:true,&quot;placeholder&quot;:true}</value>
      <webElementGuid>91dae62e-c552-465c-ad82-f3fd45524d5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>document.frm1.submit()</value>
      <webElementGuid>ff991229-4ec4-4afa-b6cd-9a6e8317053a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>83bb25aa-9bf8-48dd-a79e-5b76134d31b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-choice</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>e4795ba3-2ec6-4b93-ad1b-d56c0d6b1881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DONPEDRO</value>
      <webElementGuid>820f09df-1850-4403-bd0d-b3d403504e21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;codigosap&quot;)</value>
      <webElementGuid>73178542-f78f-4b1e-af4a-b3857df88a7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='codigosap']</value>
      <webElementGuid>f8a859cc-44ac-4540-91b9-b1576243408b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='top']/div/div/div[4]/form/div/div[3]/div[2]/div/div/div/select</value>
      <webElementGuid>9717839e-ac14-4e17-8a9f-667133826e1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clientes:'])[1]/following::select[1]</value>
      <webElementGuid>91cff368-f375-4dee-b498-e6ab3a3f9a8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='País:'])[1]/following::select[2]</value>
      <webElementGuid>40b54953-5b58-4c40-85e0-182a87f88db2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove item'])[1]/preceding::select[1]</value>
      <webElementGuid>a6d347ef-1b63-4f34-ae91-1dcb75576f80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/select</value>
      <webElementGuid>a86605a4-4c2f-40c9-b298-1ebe07534422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'codigosap' and @id = 'codigosap' and (text() = 'DONPEDRO' or . = 'DONPEDRO')]</value>
      <webElementGuid>8c79a5d5-779e-42be-9578-4c400dd349f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
