<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Seleccione.                         _09ae38</name>
   <tag></tag>
   <elementGuidId>60b5bf42-1ca7-4a6e-a7a4-8abe181eeab1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='sicasos']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sicasos</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>940113b0-d687-4012-9df9-7a176740faea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>88adb2a0-4e9e-4972-9334-8e8c86645783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sicasos</value>
      <webElementGuid>74723615-7aec-4429-a935-bd9bf8ba45d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sicasos</value>
      <webElementGuid>b4309c9e-da99-42e3-ad58-c649537e5673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                Seleccione...
                                                Si
                                                No
                                            </value>
      <webElementGuid>968b2627-1909-4e95-826d-aaa00b6b5990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sicasos&quot;)</value>
      <webElementGuid>6a82cea6-dbe6-49d9-8a5e-e0fc43e60855</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='sicasos']</value>
      <webElementGuid>4631841d-a909-4c1b-8139-5506361037f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frm']/div[9]/div/div/div/select</value>
      <webElementGuid>7783f22b-27a7-474c-bfc0-2a415b13845a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='El Usuario Atiende Casos?'])[1]/following::select[1]</value>
      <webElementGuid>564374df-7730-4f01-a92d-8c29f549068a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿El usuario es solucionador?'])[1]/following::select[1]</value>
      <webElementGuid>944c357b-847c-4afe-92ab-8d77cab982fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selecciona si el usuario va a solucionar casos de clientes'])[1]/preceding::select[1]</value>
      <webElementGuid>4431a006-923a-46be-8b64-28c5baeee598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Módulos de Acceso'])[1]/preceding::select[1]</value>
      <webElementGuid>ca89d176-d6d1-4ac3-9ae5-c9d3ed242c99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div/select</value>
      <webElementGuid>30899901-bd11-4924-9956-4a35f06bf10b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'sicasos' and @id = 'sicasos' and (text() = '
                                                Seleccione...
                                                Si
                                                No
                                            ' or . = '
                                                Seleccione...
                                                Si
                                                No
                                            ')]</value>
      <webElementGuid>21c9b9e6-4e74-4afa-a4b9-a4a92c247594</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
