<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Realizar pedido</name>
   <tag></tag>
   <elementGuidId>81b8b2c2-c809-43bd-b91d-d4c09f39c983</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='boton-uno']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#boton-uno</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1a32f6d3-25b4-4510-9ef3-29cc60562612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-falcon-default mt-2 me-2</value>
      <webElementGuid>13736e94-568d-4592-b8c0-73798c4ed132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>f1b716e8-9a00-4c75-b1b3-2dbd5765e0fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#multiCollapse1</value>
      <webElementGuid>57fd1cd1-cb7e-4107-a96d-4896f6301486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7c258c5c-6688-47fd-8641-ceb3912eab99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>64ef060f-536f-4733-a48b-e629d79d98db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>multiCollapse1</value>
      <webElementGuid>9927a325-8331-44bb-babc-d021384eb077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>boton-uno</value>
      <webElementGuid>c98430ee-afae-4de2-ad83-c5fee850f47e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Realizar pedido </value>
      <webElementGuid>64bb7a4e-56a4-4e5a-ad84-7dfa1d829c22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boton-uno&quot;)</value>
      <webElementGuid>e64a2dd4-017a-4654-9be4-c33835ce54e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='boton-uno']</value>
      <webElementGuid>f30bdc44-fa92-4125-ad38-633ea36c7517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-wizard-progress-tab1']/div/div/div/a</value>
      <webElementGuid>6af5290e-496f-4c1b-a455-34fcb1c3c7bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Realizar pedido')]</value>
      <webElementGuid>6147f612-bba9-4489-af26-05965ecfbbac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Crear una solicitud'])[1]/following::a[1]</value>
      <webElementGuid>bfb59bd1-5162-4c20-9ccd-67e7dd29e78f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gestión cliente'])[1]/following::a[1]</value>
      <webElementGuid>463d60e5-bd9b-4009-a6c5-2f545f6f63f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cargar excel'])[1]/preceding::a[1]</value>
      <webElementGuid>313d23ad-be2a-465d-91c6-bdac08c56f2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Abrir Caso'])[1]/preceding::a[1]</value>
      <webElementGuid>bf25247a-8d9d-4e09-bf96-56fe3ef2c427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Realizar pedido']/parent::*</value>
      <webElementGuid>efffb559-3b14-43ff-bfa2-089045e43d8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#multiCollapse1')]</value>
      <webElementGuid>89ce86c3-495e-4752-9f07-95adce1261ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/a</value>
      <webElementGuid>1ac52392-4911-42f3-970d-39eee7cba611</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#multiCollapse1' and @id = 'boton-uno' and (text() = 'Realizar pedido ' or . = 'Realizar pedido ')]</value>
      <webElementGuid>6518a38f-4f91-4c82-8925-e7414342b1f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
