<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cerrar_Sesion</name>
   <tag></tag>
   <elementGuidId>a78cf1f2-6291-417e-9b00-82e276ec28ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='top']/div/div/nav/ul[3]/li[5]/div/div/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6af2466c-41c2-45b7-9eb3-2141bef726f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item </value>
      <webElementGuid>fdc988ab-ffc8-4cf9-9f8a-0c07e5bd7c3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:salir()</value>
      <webElementGuid>b319d78b-01ab-4862-94b4-40ba34c39181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Salir  </value>
      <webElementGuid>be1dd260-a246-4592-83a2-eef5b3831334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;content&quot;]/nav[@class=&quot;navbar navbar-light navbar-glass navbar-top navbar-expand&quot;]/ul[@class=&quot;navbar-nav navbar-nav-icons ms-auto flex-row align-items-center&quot;]/li[@class=&quot;nav-item dropdown&quot;]/div[@class=&quot;dropdown-menu dropdown-caret dropdown-menu-end py-0 show&quot;]/div[@class=&quot;bg-white dark__bg-1000 rounded-2 py-2&quot;]/a[@class=&quot;dropdown-item&quot;]</value>
      <webElementGuid>78ae0a86-5900-4c74-822f-827601f588aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='top']/div/div/nav/ul[3]/li[5]/div/div/a[2]</value>
      <webElementGuid>86d18534-0e88-4053-9f47-f6c317ca69de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Salir')]</value>
      <webElementGuid>d286e502-fb59-4a5d-95f2-f65710151767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personalizar'])[1]/following::a[1]</value>
      <webElementGuid>be812690-7844-43c6-a438-3777a03d49b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CD'])[1]/following::a[2]</value>
      <webElementGuid>321ba233-9dcd-41bc-b162-6e9d6dae7960</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personalizar'])[2]/preceding::a[1]</value>
      <webElementGuid>4ed66815-c82d-429a-86ea-89d803d6d667</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Color'])[1]/preceding::a[1]</value>
      <webElementGuid>3d798a46-4594-481c-bd72-d4c3753399d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Salir']/parent::*</value>
      <webElementGuid>e1adb180-130e-47c5-8abb-a2a842987ebf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:salir()')]</value>
      <webElementGuid>3001ef3e-b78c-4ce6-88f9-9351655a271a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/div/div/a[2]</value>
      <webElementGuid>c3da8590-8443-4185-9fbb-565e88a88a2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:salir()' and (text() = 'Salir  ' or . = 'Salir  ')]</value>
      <webElementGuid>4b04b136-f0b7-454e-b117-a798fc5cb5a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
