<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_VIN (se recomienda ingresar este valo_33dc7e</name>
   <tag></tag>
   <elementGuidId>c9e438ab-8bfa-4c7b-bc4b-284bfe6349d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vinPedido']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vinPedido</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8c98b169-c5e1-492a-8dfe-7bc2bc514b4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8c4ce184-8273-4acf-982c-d654d95c7897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>90067ef9-8fb1-4b4b-aad6-ababfade516a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>50a054b3-25f1-4a6b-96d3-fd86e16dbe92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vinPedido</value>
      <webElementGuid>47634dd8-4449-472e-bdf6-539590c5ccb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vinPedido</value>
      <webElementGuid>ec97ce72-04f0-4c17-b3ab-68c32e55f892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>digite VIN</value>
      <webElementGuid>3b73fa84-cc2e-474e-b6c6-157f679e9bc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>dd434247-4e95-498c-8094-e68cea009c78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vinPedido&quot;)</value>
      <webElementGuid>232493de-c4b3-4ae0-a348-ecd7edc58c73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vinPedido']</value>
      <webElementGuid>12afc6f5-62b8-4dd7-a65d-6620c6ff0dc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmCreacionSolicitud']/div/div[2]/div/div/input</value>
      <webElementGuid>67e34c60-2de5-43f4-b404-28787bad09f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div/div/input</value>
      <webElementGuid>3f45b7da-46fc-41f1-a4cd-0e65e463c04d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'vinPedido' and @name = 'vinPedido' and @placeholder = 'digite VIN']</value>
      <webElementGuid>8bd23156-648c-4afc-b3dc-155270dfb1bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
