<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Marca versin y modelo_marcaPedido</name>
   <tag></tag>
   <elementGuidId>41bb0329-1e23-4e25-b197-d6b7b210354b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='marcaPedido']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#marcaPedido</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bbee41e6-7541-4237-b7b9-c76b36f675d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b4350b1f-12fd-4c3a-8cca-ec3ab586a2c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>36be9f54-d8f3-4891-9460-011abf84ed73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d23e6bd2-1796-4017-a8af-6adac1aed234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>marcaPedido</value>
      <webElementGuid>1295309e-85f9-40e3-a0b1-f62538290f40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>marcaPedido</value>
      <webElementGuid>dde88f54-2b7e-49cb-9555-12350dd0fcd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mercedes-Benz CLE 300 4MATIC Mod 2023  </value>
      <webElementGuid>50fdad5d-329e-4d46-97bf-8db716dddfba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;marcaPedido&quot;)</value>
      <webElementGuid>6d9d23a6-1959-439b-8527-f28841f8b55d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='marcaPedido']</value>
      <webElementGuid>83601283-79fa-416f-9506-97d477d025ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmCreacionSolicitud']/div/div[2]/div[2]/div/input</value>
      <webElementGuid>dc53d32e-f99e-4a7c-9a22-f217d3753834</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>3dd3f21c-a636-481c-8617-aa4ee8f43126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'marcaPedido' and @name = 'marcaPedido' and @placeholder = 'Mercedes-Benz CLE 300 4MATIC Mod 2023  ']</value>
      <webElementGuid>d84510fc-8a25-4e7e-90a2-5d148536ea52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
