<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>spinnerFormularioExcel</name>
   <tag></tag>
   <elementGuidId>181dad8e-88d1-443f-94c3-19f978e595f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div/div/div[6]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.swal2-loader</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8cb2f9c1-886e-4adf-8af1-a00535cfd582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>swal2-loader</value>
      <webElementGuid>b94f69ac-ed56-4746-8731-7513e3a657c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-button-to-replace</name>
      <type>Main</type>
      <value>swal2-confirm swal2-styled</value>
      <webElementGuid>c5d91822-1042-4a1b-917e-78d03de8f755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;chrome windows fontawesome-i2svg-active fontawesome-i2svg-complete swal2-shown swal2-height-auto&quot;]/body[@class=&quot;swal2-shown swal2-height-auto&quot;]/div[@class=&quot;swal2-container swal2-center swal2-backdrop-show&quot;]/div[@class=&quot;swal2-popup swal2-modal swal2-loading swal2-show&quot;]/div[@class=&quot;swal2-actions swal2-loading&quot;]/div[@class=&quot;swal2-loader&quot;]</value>
      <webElementGuid>cfc685b1-fcf5-4b9d-a61e-2a692413d314</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/div/div/div[6]/div</value>
      <webElementGuid>9afce32f-39fd-4c9b-ba47-923970ad8b99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
